#!/usr/bin/env python3
"""Generate a deterministic repository inventory for coding agents."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "agent" / "repository-index.md"

EXCLUDED_PARTS = {
    ".git",
    ".gradle",
    ".idea",
    "build",
    "out",
    "target",
    "node_modules",
    "__pycache__",
    ".agent-backups",
}

GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Top-level project files", (
        "README.md",
        "START-HERE.md",
        "AI-DLC.md",
        "AI-DLC-INSTALLATION.md",
        "build.gradle.kts",
        "settings.gradle.kts",
        "gradle.properties",
        "gradlew",
        "gradlew.bat",
        "setup-project.ps1",
    )),
    ("Canonical project context", (
        ".ai/*.md",
        ".ai/decisions/*.md",
    )),
    ("Project Java source", (
        "src/main/java/**/*.java",
    )),
    ("Project resources", (
        "src/main/resources/**/*",
    )),
    ("Project tests", (
        "src/test/**/*.java",
        "src/test/resources/**/*",
    )),
    ("Gradle wrapper", (
        "gradle/wrapper/**/*",
    )),
    ("Agent documentation and review", (
        "docs/agent/*.md",
        "REVIEW.md",
    )),
    ("Agent contract, adapters, and skills", (
        "AGENTS.md",
        "CLAUDE.md",
        "GEMINI.md",
        ".aiassistant/rules/**/*",
        ".amazonq/rules/**/*",
        ".agents/skills/**/*",
        ".claude/skills/**/*",
        ".clinerules/**/*",
        ".continue/rules/**/*",
        ".cursor/rules/**/*",
        ".cursor/skills/**/*",
        ".github/agents/**/*",
        ".github/copilot-instructions.md",
        ".github/instructions/**/*",
        ".github/skills/**/*",
        ".junie/**/*",
        ".windsurf/rules/**/*",
        ".windsurf/skills/**/*",
    )),
    ("Agent automation and CI", (
        "setup-agent.ps1",
        "setup-agent.sh",
        "scripts/agent_file_manifest.txt",
        "scripts/agent_validate.*",
        "scripts/refresh_agent_index.py",
        "scripts/verify_agent_contract.py",
        "scripts/verify-agent-docs.*",
        ".github/workflows/agent-context.yml",
        ".github/pull_request_template.md",
    )),
)


def is_included(path: Path) -> bool:
    if not path.is_file():
        return False
    if path.resolve() == OUTPUT.resolve():
        return False
    relative = path.relative_to(ROOT)
    return not any(part in EXCLUDED_PARTS for part in relative.parts)


def collect(patterns: tuple[str, ...]) -> list[str]:
    found: set[str] = set()
    for pattern in patterns:
        for path in ROOT.glob(pattern):
            if is_included(path):
                found.add(path.relative_to(ROOT).as_posix())
    return sorted(found, key=lambda value: (value.lower(), value))


def render() -> str:
    lines = [
        "# Variable Radius Circle Workspace Repository Index",
        "",
        "Generated by `scripts/refresh_agent_index.py`. Do not hand-edit.",
        "",
        "This inventory helps coding agents discover relevant files. It does not replace source inspection, `AGENTS.md`, the canonical `.ai/` documents, or `docs/agent/feature-map.md`.",
        "",
    ]
    for title, patterns in GROUPS:
        paths = collect(patterns)
        lines.extend((f"## {title}", ""))
        if paths:
            lines.extend(f"- `{path}`" for path in paths)
        else:
            lines.append("- _No matching files found._")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the generated index differs from the checked-in file.",
    )
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists():
            print(f"ERROR: Missing {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != content:
            print(
                "ERROR: docs/agent/repository-index.md is stale. "
                "Run: python scripts/refresh_agent_index.py",
                file=sys.stderr,
            )
            return 1
        print("Repository index is current.")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Updated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
